# References:
#
# https://blog.argoproj.io/draft-argo-cd-v2-6-release-candidate-ced1853bbfdb
# https://github.com/argoproj/argo-cd/issues/2531
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
    - resources-finalizer.argocd.argoproj.io
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/projects/
  project: default
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.1
    helm:
      valueFiles:
      - $values/helm-apps/argocd/ingress-nginx/values.yaml
  - repoURL: https://github.com/aeciopires/learning-victoriametrics
    # Branch or tag name
    targetRevision: main
    ref: values
  # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
    - CreateNamespace=true
