global:
  domain: argocd.mycompany.com
  # Default image used by all components
  image:
    # -- If defined, a repository applied to all Argo CD deployments
    repository: quay.io/argoproj/argocd
    # -- Overrides the global Argo CD image tag whose default is the chart appVersion
    tag: "v3.0.0"
    # -- If defined, a imagePullPolicy applied to all Argo CD deployments
    imagePullPolicy: IfNotPresent

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      #--- Annotations to use nginx-ingress
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: / # URL redirection
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # Force redirect to HTTPS
      nginx.ingress.kubernetes.io/ssl-redirect: "true" # SSL redirection enabled
      #--- Optional Annotation for cert-manager
      cert-manager.io/cluster-issuer: "letsencrypt-prod-http01" # Using Let's Encrypt for the certificate
    extraTls:
      - hosts:
        - argocd.mycompany.com
        # Based on the ingress controller used secret might be optional
        secretName: argocd-tls-secret